export const data = {
  day1: [
    require('./src/data/day1/workout-15-5.gif'),
    require('./src/data/day1/workout-50-5.gif'),
    require('./src/data/day1/workout-87-5.gif'),
    require('./src/data/day1/workout-110-5.gif'),
    require('./src/data/day1/workout-131-5.gif'),
    require('./src/data/day1/workout-275-5.gif'),
    require('./src/data/day1/workout-443-5.gif'),
    require('./src/data/day1/workout-444-5.gif'),
  ],
  day2: [
    require('./src/data/day2/workout-2-5.gif'),
    require('./src/data/day2/workout-40-5.gif'),
    require('./src/data/day2/workout-111-5.gif'),
    require('./src/data/day2/workout-123-5.gif'),
    require('./src/data/day2/workout-182-5.gif'),
    require('./src/data/day2/workout-405-5.gif'),
    require('./src/data/day2/workout-406-5.gif'),
  ],
  day3: [
    require('./src/data/day3/workout-15-5.gif'),
    require('./src/data/day3/workout-50-5.gif'),
    require('./src/data/day3/workout-61-5.gif'),
    require('./src/data/day3/workout-110-5.gif'),
    require('./src/data/day3/workout-111-5.gif'),
    require('./src/data/day3/workout-123-5.gif'),
  ],
  day4: [
    require('./src/data/day4/workout-2-5.gif'),
    require('./src/data/day4/workout-110-5.gif'),
    require('./src/data/day4/workout-111-5.gif'),
    require('./src/data/day4/workout-275-5.gif'),
  ],
  day5: [
    require('./src/data/day5/workout-26-5.gif'),
    require('./src/data/day5/workout-110-5.gif'),
    require('./src/data/day5/workout-123-5.gif'),
    require('./src/data/day5/workout-171-5.gif'),
    require('./src/data/day5/workout-185-5.gif'),
    require('./src/data/day5/workout-186-5.gif'),
  ],
  day6: [
    require('./src/data/day6/workout-111-5.gif'),
    require('./src/data/day6/workout-123-5.gif'),
    require('./src/data/day6/workout-182-5.gif'),
    require('./src/data/day6/workout-275-5.gif'),
    require('./src/data/day6/workout-390-5.gif'),
    require('./src/data/day6/workout-391-5.gif'),
  ],
  day7: [
    require('./src/data/day7/workout-15-5.gif'),
    require('./src/data/day7/workout-110-5.gif'),
    require('./src/data/day7/workout-123-5.gif'),
    require('./src/data/day7/workout-131-5.gif'),
    require('./src/data/day7/workout-282-5.gif'),
    require('./src/data/day7/workout-405-5.gif'),
    require('./src/data/day7/workout-406-5.gif'),
  ],
};
